### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by HLHsieh** [kolikem/loma#6]
Hi,

I war trying to run the following command

```
sh $loma -I fastq -O loma -H $minimap2 -K $mafft
```

Some errors returned
```
-H defined:  /nfs/turbo/umms-kinfai/yunhwang/Source/OSC/minimap2-2.24_x64-linux/minimap2
-K defined:  ~/miniconda3/bin/mafft
-I defined:  fastq
-O defined:  loma
-b not defined. default value is used:  3000
-s not defined. default value is used:  2000
-h not defined. default value is used:  10
-d not defined. default value is used:  3
-l not defined. default value is used:  ont
-c not defined. default value is used:  0.7
-r not defined. default value is used:  0.5
-m not defined. default value is used:  1000
code directory /nfs/turbo/umms-kinfai/hsinlun/bin/loma/loma_src
mkdir: cannot create directory ‘loma/dir1’: No such file or directory
mkdir: cannot create directory ‘loma/dir2’: No such file or directory
mkdir: cannot create directory ‘loma/CONSENSUS’: No such file or directory
mkdir: cannot create directory ‘loma/dir2/fastq2nd’: No such file or directory
/nfs/turbo/umms-kinfai/hsinlun/bin/loma/loma: line 62: cd: loma/dir1: No such file or directory
/nfs/turbo/umms-kinfai/hsinlun/bin/loma/loma: line 66: loma/dir1/*fastq.out1: No such file or directory
fastq file : *fastq
region name : *fastq
Runnig command: python3 /nfs/turbo/umms-kinfai/hsinlun/bin/loma/loma_src/EsS.py fastq/*fastq loma/dir1/*fastq.out1 0.04 3000 2000 0.7 0.5 loma/dir1 1000
---EsS.py---
Traceback (most recent call last):
  File "/nfs/turbo/umms-kinfai/hsinlun/bin/loma/loma_src/EsS2.py", line 45, in <module>
    file_fastq = open(sys.argv[1])
FileNotFoundError: [Errno 2] No such file or directory: 'fastq/*fastq'
/nfs/turbo/umms-kinfai/hsinlun/bin/loma/loma: line 75: loma/dir1/*fastq.out2.*: No such file or directory
---LGS.py---
Traceback (most recent call last):
  File "/nfs/turbo/umms-kinfai/hsinlun/bin/loma/loma_src/LGS3.py", line 11, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
Running command: ~/miniconda3/bin/mafft --op 0 --ep 1 --thread 8 --threadit 0 loma/dir1/*fastq.out7.* > loma/dir1/*fastq.out7.*
/nfs/turbo/umms-kinfai/hsinlun/bin/loma/loma: line 86: loma/dir1/*fastq.out7.*: No such file or directory
---SCM2.py---
Traceback (most recent call last):
  File "/nfs/turbo/umms-kinfai/hsinlun/bin/loma/loma_src/SCM2.py", line 313, in <module>
    main()
  File "/nfs/turbo/umms-kinfai/hsinlun/bin/loma/loma_src/SCM2.py", line 299, in main
    reads, names = get_aln_reads()
  File "/nfs/turbo/umms-kinfai/hsinlun/bin/loma/loma_src/SCM2.py", line 26, in get_aln_reads
    f = open(sys.argv[2])
FileNotFoundError: [Errno 2] No such file or directory: 'loma/dir1/*fastq.out8.*'
rm: cannot remove 'loma/dir1/*fastq*out2*': No such file or directory
rm: cannot remove 'loma/dir1/*fastq*out3*': No such file or directory
rm: cannot remove 'loma/dir1/*fastq*out7*': No such file or directory
ls: cannot access 'loma/dir1/*fastq.out4.*': No such file or directory
input parameters
block size: 3000
step size: 2000
number of blocks: 0
cp: cannot stat 'loma/dir1/*fastq.out4.1': No such file or directory
Traceback (most recent call last):
  File "/nfs/turbo/umms-kinfai/hsinlun/bin/loma/loma_src/RCS2.py", line 132, in <module>
    make_init_concat()
  File "/nfs/turbo/umms-kinfai/hsinlun/bin/loma/loma_src/RCS2.py", line 23, in make_init_concat
    subprocess.check_call(cmd, shell=True)
  File "/sw/spack/bio/pkgs/gcc-10.3.0/python/3.9.7-rv5ybzg3/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cp loma/dir1/*fastq.out4.1 loma/dir1/*fastq.concat.1' returned non-zero exit status 1.
rm: cannot remove 'loma/dir1/*fastq*out8*': No such file or directory
rm: cannot remove 'loma/dir1/*.concat.*': No such file or directory
rm: cannot remove 'loma/dir1/*.out4.*': No such file or directory
rm: cannot remove 'loma/dir1/*.out4a.*': No such file or directory
rm: cannot remove 'loma/dir1/*.tail_head.*': No such file or directory
mkdir: cannot create directory ‘loma/dir2/sam2nd’: No such file or directory
/nfs/turbo/umms-kinfai/hsinlun/bin/loma/loma: line 116: loma/dir2/sam2nd/*_map_on_1st_cs.sam: No such file or directory
---ReadClassify.py---
Traceback (most recent call last):
  File "/nfs/turbo/umms-kinfai/hsinlun/bin/loma/loma_src/ReadClassify6.py", line 10, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
/nfs/turbo/umms-kinfai/hsinlun/bin/loma/loma: line 123: cd: loma/dir2: No such file or directory
ls: cannot access 'loma/dir2/fastq2nd': No such file or directory
3rd step finished. No hetero region detected.
mv: cannot stat 'loma/dir1/*.cs': No such file or directory
time to finish 1st CS: 2
time to finish read classification: 0
time to finish 2nd CS: 0
total time: 2
```
Any suggestions would be appreciated.

Best,
Hsin

**Comment by kolikem** [comment]
Hi, Hsin

Thank you for contacting us.

The error message says "mkdir: cannot create directory ‘loma/dir1’: No such file or directory". Could you check if you have made "loma" directory for output?

Please tell me if you have any more problems.

Ko

**Comment by HLHsieh** [comment]
Yes. I have created a loma folder before running the the command. Moreover, even if I created all subfolders, I still got the following error message:

```
-H defined:  /nfs/turbo/umms-kinfai/yunhwang/Source/OSC/minimap2-2.24_x64-linux/minimap2
-K defined:  ~/miniconda3/bin/mafft
-I defined:  fastq
-O defined:  loma
-b not defined. default value is used:  3000
-s not defined. default value is used:  2000
-h not defined. default value is used:  10
-d not defined. default value is used:  3
-l not defined. default value is used:  ont
-c not defined. default value is used:  0.7
-r not defined. default value is used:  0.5
-m not defined. default value is used:  1000
code directory /nfs/turbo/umms-kinfai/hsinlun/bin/loma/loma_src
/nfs/turbo/umms-kinfai/hsinlun/bin/loma/loma: line 66: loma/dir1/*fastq.out1: No such file or directory
fastq file : *fastq
region name : *fastq
Runnig command: python3 /nfs/turbo/umms-kinfai/hsinlun/bin/loma/loma_src/EsS.py fastq/*fastq loma/dir1/*fastq.out1 0.04 3000 2000 0.7 0.5 loma/dir1 1000
---EsS.py---
Traceback (most recent call last):
  File "/nfs/turbo/umms-kinfai/hsinlun/bin/loma/loma_src/EsS2.py", line 45, in <module>
    file_fastq = open(sys.argv[1])
FileNotFoundError: [Errno 2] No such file or directory: 'fastq/*fastq'
/nfs/turbo/umms-kinfai/hsinlun/bin/loma/loma: line 75: loma/dir1/*fastq.out3.*: No such file or directory
---LGS.py---
imported modules
Traceback (most recent call last):
  File "/nfs/turbo/umms-kinfai/hsinlun/bin/loma/loma_src/LGS3.py", line 129, in <module>
    names, reads = preprocess()
  File "/nfs/turbo/umms-kinfai/hsinlun/bin/loma/loma_src/LGS3.py", line 20, in preprocess
    f = open(sys.argv[1])       # e.g. ST3GAL3_novel_0_ATL7.fastq.out3.2
FileNotFoundError: [Errno 2] No such file or directory: 'loma/dir1/*fastq.out3.*'
Running command: ~/miniconda3/bin/mafft --op 0 --ep 1 --thread 8 --threadit 0 loma/dir1/*fastq.out7.* > loma/dir1/*fastq.out8.*
/nfs/turbo/umms-kinfai/hsinlun/bin/loma/loma: line 86: loma/dir1/*fastq.out8.*: No such file or directory
---SCM2.py---
Traceback (most recent call last):
  File "/nfs/turbo/umms-kinfai/hsinlun/bin/loma/loma_src/SCM2.py", line 313, in <module>
    main()
  File "/nfs/turbo/umms-kinfai/hsinlun/bin/loma/loma_src/SCM2.py", line 299, in main
    reads, names = get_aln_reads()
  File "/nfs/turbo/umms-kinfai/hsinlun/bin/loma/loma_src/SCM2.py", line 26, in get_aln_reads
    f = open(sys.argv[2])
FileNotFoundError: [Errno 2] No such file or directory: 'loma/dir1/*fastq.out8.*'
rm: cannot remove 'loma/dir1/*fastq*out2*': No such file or directory
rm: cannot remove 'loma/dir1/*fastq*out3*': No such file or directory
rm: cannot remove 'loma/dir1/*fastq*out7*': No such file or directory
ls: cannot access 'loma/dir1/*fastq.out4.*': No such file or directory
input parameters
block size: 3000
step size: 2000
number of blocks: 0
cp: cannot stat 'loma/dir1/*fastq.out4.1': No such file or directory
Traceback (most recent call last):
  File "/nfs/turbo/umms-kinfai/hsinlun/bin/loma/loma_src/RCS2.py", line 132, in <module>
    make_init_concat()
  File "/nfs/turbo/umms-kinfai/hsinlun/bin/loma/loma_src/RCS2.py", line 23, in make_init_concat
    subprocess.check_call(cmd, shell=True)
  File "/sw/spack/bio/pkgs/gcc-10.3.0/python/3.9.7-rv5ybzg3/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cp loma/dir1/*fastq.out4.1 loma/dir1/*fastq.concat.1' returned non-zero exit status 1.
rm: cannot remove 'loma/dir1/*fastq*out8*': No such file or directory
rm: cannot remove 'loma/dir1/*.concat.*': No such file or directory
rm: cannot remove 'loma/dir1/*.out4.*': No such file or directory
rm: cannot remove 'loma/dir1/*.out4a.*': No such file or directory
rm: cannot remove 'loma/dir1/*.tail_head.*': No such file or directory
mkdir: cannot create directory ‘loma/dir2/sam2nd’: No such file or directory
/nfs/turbo/umms-kinfai/hsinlun/bin/loma/loma: line 116: loma/dir2/sam2nd/*_map_on_1st_cs.sam: No such file or directory
---ReadClassify.py---
Traceback (most recent call last):
  File "/nfs/turbo/umms-kinfai/hsinlun/bin/loma/loma_src/ReadClassify6.py", line 279, in <module>
    f = open(sys.argv[1])
FileNotFoundError: [Errno 2] No such file or directory: 'loma/dir2/sam2nd/*_map_on_1st_cs.sam'
/nfs/turbo/umms-kinfai/hsinlun/bin/loma/loma: line 123: cd: loma/dir2: No such file or directory
ls: cannot access 'loma/dir2/fastq2nd': No such file or directory
3rd step finished. No hetero region detected.
mv: cannot stat 'loma/dir1/*.cs': No such file or directory
time to finish 1st CS: 4
time to finish read classification: 1
time to finish 2nd CS: 0
total time: 5
```

**Comment by kolikem** [comment]
Hsin, 

Thank you for sharing your situation.

I would appreciate if you could make sure some points concerning this problem.
(1) Please download the latest version v1.1.3 from Releases.
(2) whether the input (fastq) and output directory are given by their _**absolute path**_.
(3) whether the libraries, numpy and matplotlib are in your environment.

Sorry for the inconvenience. Hope it works right.
Please ask anytime.

Best regards,
Ko

**Comment by HLHsieh** [comment]
Thank you for your suggestions. All errors have been resolved.

However, when running the command sh /nfs/turbo/bin/loma-1.1.3/loma -I /scratch/D4Z4_4_9R_NanoSim_30x/fastq -O /scratch/D4Z4_4_9R_NanoSim_30x/loma, it took more than three days. I am wondering if there is any way to speed up the process.

Thank you,
Hsin

**Comment by kolikem** [comment]
Hsin,

Thank you for your comment.
As our simulation suggested, reconstructions of targets sized < 100 kbp take less than 10 minutes on average, which is of course dependent on input data coverage. Basically, the step that controls the whole time of processes is overlapping and layout of reads, and multiple alignment of binned windows.
Using a highly repetitive sequence as input might take unexpectedly long time although we have never experienced it. And it might take a lengthy time if a target spans a wide stretch of genomic region.

Best,
Ko

**Comment by HLHsieh** [comment]
Hi Ko,

Thanks for the information. It seems that I'll need to filter the input FASTQ files first to include only those from localized regions. This is because I apply the whole FASTQ dataset to the tool. LoMA is a tool for localized assembly, but I didn't see any parameter to specify the region of interest. Do you have any suggestions on how to find the FASTQ files of interest and apply them to LoMA?

Best,
Hsin

**Comment by kolikem** [comment]
Hsin,

A way to find reads that come from ROI is to simply align the FASTQ files to the reference and extract ones mapped to ROI using analysis tools such as samtools. Otherwise, like when the reference genome is not available, or when mapping the whole data takes too long time, instead you can construct a fill-in nucleotide sequence which is long enough for prospective reads to be mapped to, and align the FASTQ to it. The fill-in can be a raw read that is surely derived from the ROI though there could be no systematic way to find the first one.

Best regards,
Ko

**Comment by HLHsieh** [comment]
Hi Ko,

I've successfully executed loma on my own data. I obtained three folders: CONSENSUS, dir1, and dir2. Could you provide a brief explanation of how to interpret these results/files? Additionally, I noticed a file named loma.fastq.cs in the CONSENSUS folder with numbers such as 1, 1, 1, 1, 1, 2, 2, 2, 3, 4, 4, 5, 7, 9, 11, 15, 23, 29, 50, 32, 15, 11, 10, 7, 3, 3, 2, 2, 1, 1. Could you clarify what these numbers represent?

Thank you.
